spring.application.name=gateway-service
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port=8888
server.address: 0.0.0.0

# NEW KEY FORMATS for Spring Cloud 2025.0.0
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# Route 0 for /auth/login
spring.cloud.gateway.server.webflux.routes[0].id=startup-auth-login
spring.cloud.gateway.server.webflux.routes[0].uri=lb://startup-authentication-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Route 1 for /api/v1/users (exact match)
spring.cloud.gateway.server.webflux.routes[1].id=startup-user-root
spring.cloud.gateway.server.webflux.routes[1].uri=lb://startup-authentication-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users

spring.cloud.gateway.server.webflux.routes[2].id=startup-user-root
spring.cloud.gateway.server.webflux.routes[2].uri=lb://startup-authentication-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/users/**


#// CRM APP CONFIGURATIONS

spring.cloud.gateway.server.webflux.routes[3].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/chat/messages/**

spring.cloud.gateway.server.webflux.routes[4].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notifications/**

spring.cloud.gateway.server.webflux.routes[5].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/checkin/**

spring.cloud.gateway.server.webflux.routes[6].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/checkout/**

spring.cloud.gateway.server.webflux.routes[7].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/emp/**

spring.cloud.gateway.server.webflux.routes[8].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/chat/groups/**

spring.cloud.gateway.server.webflux.routes[9].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/lists/**

spring.cloud.gateway.server.webflux.routes[10].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[10].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/reminders/**

spring.cloud.gateway.server.webflux.routes[11].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[11].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/spaces/**

spring.cloud.gateway.server.webflux.routes[12].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[12].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/tasks/**

spring.cloud.gateway.server.webflux.routes[13].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[13].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/tickets/**

spring.cloud.gateway.server.webflux.routes[14].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[14].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/workspaces/**

spring.cloud.gateway.server.webflux.routes[17].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[17].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/project/**

spring.cloud.gateway.server.webflux.routes[18].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[18].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[18].predicates[0]=Path=/timesheet

spring.cloud.gateway.server.webflux.routes[19].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[19].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[19].predicates[0]=Path=/timesheet/**

spring.cloud.gateway.server.webflux.routes[20].id=startup-meeting-api
spring.cloud.gateway.server.webflux.routes[20].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[20].predicates[0]=Path=/meetings/**

spring.cloud.gateway.server.webflux.routes[21].id=startup-meeting-websocket
spring.cloud.gateway.server.webflux.routes[21].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[21].predicates[0]=Path=/ws/**


spring.cloud.gateway.server.webflux.routes[22].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[22].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[22].predicates[0]=Path=/api/leaves/**

# ORG APP CONFIGURATIONS


spring.cloud.gateway.server.webflux.routes[15].id=startup-organization-service
spring.cloud.gateway.server.webflux.routes[15].uri=lb://startup-organization-service
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/org

spring.cloud.gateway.server.webflux.routes[16].id=startup-organization-service
spring.cloud.gateway.server.webflux.routes[16].uri=lb://startup-organization-service
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/org/**

logging.level.org.springframework.cloud.gateway=DEBUG

# NOTE : predicates[0],predicates[1] considering as AND so we have separate route for each unique in same service

jwt.secretKey= lvzCf61j4U9su4FSyzzjRS6yOVKwUCwxxS9y59h5rGQ=
jwt.expirationMs=3600000
jwt.refreshExpirationMs=86400000


# for Allow UI

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins[0]=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins[1]=http://startahb.com
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins[2]=http://3.108.55.79:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins[3]=https://startahb.com
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins[4]=https://3.108.55.79:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders[0]=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true










