spring.application.name=gateway-service
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port=8888

# NEW KEY FORMATS for Spring Cloud 2025.0.0
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# Route 0 for /auth/login
spring.cloud.gateway.server.webflux.routes[0].id=startup-auth-login
spring.cloud.gateway.server.webflux.routes[0].uri=lb://startup-authentication-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Route 1 for /api/v1/users (exact match)
spring.cloud.gateway.server.webflux.routes[1].id=startup-user-root
spring.cloud.gateway.server.webflux.routes[1].uri=lb://startup-authentication-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users

spring.cloud.gateway.server.webflux.routes[2].id=startup-user-root
spring.cloud.gateway.server.webflux.routes[2].uri=lb://startup-authentication-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[3].id=startup-crm-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://startup-crm-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/crm/**

spring.cloud.gateway.server.webflux.routes[4].id=startup-organization-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://startup-organization-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/org

spring.cloud.gateway.server.webflux.routes[5].id=startup-organization-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://startup-organization-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/org/**

logging.level.org.springframework.cloud.gateway=DEBUG

# NOTE : predicates[0],predicates[1] considering as AND so we have separate route for each unique in same service

jwt.secretKey= lvzCf61j4U9su4FSyzzjRS6yOVKwUCwxxS9y59h5rGQ=
jwt.expirationMs=3600000
jwt.refreshExpirationMs=86400000